# Generated by Django 5.0.6 on 2024-06-28 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_peluqueria', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
