# Generated by Django 5.0.6 on 2024-06-28 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_peluqueria', '0004_carritoitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarritoItem',
        ),
    ]
