# Generated by Django 5.0.6 on 2024-06-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_peluqueria', '0007_alter_producto_imagen_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
